### ISSUE TITLE
Contribute Logistic Regression on MNIST 

### ISSUE THREAD

**Issue by ghost** [studentcontributions/MNIST-model-comparison#3]
# contributor needed ASAP

**Comment by jesherjoshua** [comment]
@studentcontributions what frameworks can I use? can I use torch.nn.linear? or is strictly sklearn?

**Comment by ghost** [comment]
anything works @jesherjoshua

**Comment by jesherjoshua** [comment]
Can you assign me ?

**Comment by ghost** [comment]
good job @jesherjoshua
